import type { CertificationPack } from '../../core/types';

// Contenido original de DEMOSTRACIÓN. Pendiente de revisión editorial antes de
// utilizarlo como banco de preparación para la certificación CAPM.
export const capm: CertificationPack = {
  id: 'capm', title: 'CAPM', subtitle: 'Certified Associate in Project Management',
  questions: [
    { id: 'CAPM-DEMO-001', domain: 'Fundamentos', topic: 'Conceptos', difficulty: 'basico', prompt: '¿Qué caracteriza a un proyecto?', options: ['Es un esfuerzo temporal para crear un resultado único', 'Es una operación continua y repetitiva', 'No tiene objetivos definidos', 'Siempre dura menos de un año'], correct: 0, explanation: 'Un proyecto es un esfuerzo temporal orientado a producir un producto, servicio o resultado único.' },
    { id: 'CAPM-DEMO-002', domain: 'Fundamentos', topic: 'Roles', difficulty: 'basico', prompt: '¿Cuál es una responsabilidad habitual del patrocinador del proyecto?', options: ['Escribir cada actividad del cronograma', 'Proporcionar apoyo y facilitar recursos a nivel ejecutivo', 'Realizar todas las pruebas técnicas', 'Sustituir a todos los interesados'], correct: 1, explanation: 'El patrocinador apoya el proyecto a nivel ejecutivo y facilita su alineación y recursos.' },
    { id: 'CAPM-DEMO-003', domain: 'Enfoques predictivos', topic: 'Alcance', difficulty: 'basico', prompt: '¿Para qué se utiliza una EDT (WBS)?', options: ['Priorizar automáticamente el backlog', 'Medir la satisfacción del equipo', 'Descomponer el alcance en componentes manejables', 'Definir los salarios del proyecto'], correct: 2, explanation: 'La estructura de desglose del trabajo organiza el alcance en entregables y componentes más pequeños.' },
    { id: 'CAPM-DEMO-004', domain: 'Enfoques ágiles', topic: 'Scrum', difficulty: 'basico', prompt: '¿Qué representa el Product Backlog?', options: ['Un registro exclusivo de problemas cerrados', 'Una lista ordenada del trabajo necesario para mejorar el producto', 'El calendario de vacaciones', 'Una lista inmutable que nunca cambia'], correct: 1, explanation: 'El Product Backlog es una lista ordenada y evolutiva del trabajo necesario para mejorar el producto.' },
    { id: 'CAPM-DEMO-005', domain: 'Análisis de negocio', topic: 'Requisitos', difficulty: 'basico', prompt: '¿Qué describe un requisito?', options: ['Una condición o capacidad necesaria para una solución', 'Un costo ya ejecutado', 'La fecha de cierre de cualquier proyecto', 'Una tarea sin relación con el producto'], correct: 0, explanation: 'Un requisito representa una condición o capacidad necesaria para satisfacer una necesidad.' },
    { id: 'CAPM-DEMO-006', domain: 'Fundamentos', topic: 'Interesados', difficulty: 'basico', prompt: '¿Quién puede considerarse interesado de un proyecto?', options: ['Únicamente el director del proyecto', 'Solamente el cliente que paga', 'Una persona o grupo que puede afectar o verse afectado por el proyecto', 'Solo integrantes del equipo interno'], correct: 2, explanation: 'Los interesados incluyen personas o grupos que pueden influir o verse afectados por el proyecto.' },
    { id: 'CAPM-DEMO-007', domain: 'Enfoques predictivos', topic: 'Valor ganado', difficulty: 'intermedio', prompt: 'Un proyecto tiene EV = 80 y AC = 100. ¿Cuál es el CPI?', options: ['1,25', '0,80', '20', '180'], correct: 1, explanation: 'CPI = EV / AC = 80 / 100 = 0,80; indica eficiencia de costos inferior a 1.' },
    { id: 'CAPM-DEMO-008', domain: 'Enfoques ágiles', topic: 'Priorización', difficulty: 'intermedio', prompt: 'Un equipo recibe un requisito urgente durante una iteración. ¿Qué respuesta es más coherente con Scrum?', options: ['Modificar el Sprint Goal sin consultar al equipo', 'Cancelar automáticamente el proyecto', 'Conversar con el Product Owner y negociar el alcance sin comprometer el Sprint Goal', 'Añadirlo de manera unilateral y omitir la revisión'], correct: 2, explanation: 'El alcance puede aclararse o renegociarse con el Product Owner a medida que se aprende, sin poner en peligro el objetivo del Sprint.' },
    { id: 'CAPM-DEMO-009', domain: 'Fundamentos', topic: 'Riesgos', difficulty: 'intermedio', prompt: 'Un evento incierto, que si ocurre puede afectar los objetivos del proyecto, es:', options: ['Un problema ya materializado', 'Un riesgo', 'Un entregable aprobado', 'Una línea base'], correct: 1, explanation: 'El riesgo es incierto; un problema describe una situación que ya está ocurriendo.' },
    { id: 'CAPM-DEMO-010', domain: 'Análisis de negocio', topic: 'Trazabilidad', difficulty: 'intermedio', prompt: '¿Para qué sirve una matriz de trazabilidad de requisitos?', options: ['Eliminar cualquier cambio', 'Sustituir la validación del usuario', 'Vincular requisitos con sus fuentes, entregables y verificaciones', 'Calcular el CPI'], correct: 2, explanation: 'La trazabilidad permite seguir cada requisito a través de su origen, implementación y verificación.' },
    { id: 'CAPM-DEMO-011', domain: 'Enfoques predictivos', topic: 'Cronograma', difficulty: 'intermedio', prompt: '¿Qué indica una holgura total igual a cero en una ruta crítica convencional?', options: ['Las actividades pueden retrasarse sin impacto', 'Que esa ruta define la duración mínima del proyecto según el modelo', 'Que la actividad carece de dependencias', 'Que el costo del proyecto será cero'], correct: 1, explanation: 'En el modelo de ruta crítica, las actividades de una ruta crítica no tienen holgura total disponible sin afectar la fecha final prevista.' },
    { id: 'CAPM-DEMO-012', domain: 'Enfoques ágiles', topic: 'Flujo', difficulty: 'intermedio', prompt: '¿Qué busca principalmente limitar el trabajo en curso (WIP) en Kanban?', options: ['Aumentar las tareas abiertas sin terminarlas', 'Eliminar la necesidad de colaboración', 'Favorecer el flujo y evitar la sobrecarga del sistema', 'Impedir medir el tiempo de entrega'], correct: 2, explanation: 'Los límites de WIP ayudan a gestionar el flujo, detectar cuellos de botella y reducir el trabajo simultáneo.' },
    { id: 'CAPM-DEMO-013', domain: 'Fundamentos', topic: 'Cambios', difficulty: 'avanzado', prompt: 'Un cambio solicitado afecta alcance, costo y fecha en un proyecto predictivo. ¿Qué debería hacerse primero?', options: ['Modificar las líneas base sin registrar el cambio', 'Analizar los impactos y seguir el proceso de control de cambios acordado', 'Pedir al equipo que lo implemente sin comunicarlo', 'Cerrar el proyecto automáticamente'], correct: 1, explanation: 'Antes de modificar líneas base, se evalúan los impactos y se aplica el control integrado de cambios definido para el proyecto.' },
    { id: 'CAPM-DEMO-014', domain: 'Enfoques predictivos', topic: 'Pronósticos', difficulty: 'avanzado', prompt: 'BAC = 200, EV = 100, AC = 125. Si continúa el CPI actual, ¿cuál es el EAC aproximado?', options: ['160', '200', '225', '250'], correct: 3, explanation: 'CPI = 100/125 = 0,8; con el supuesto de rendimiento constante, EAC = BAC/CPI = 250.' },
    { id: 'CAPM-DEMO-015', domain: 'Enfoques ágiles', topic: 'Scrum', difficulty: 'avanzado', prompt: 'Durante un Sprint, surge trabajo nuevo que haría obsoleto el Sprint Goal. ¿Quién puede cancelar el Sprint?', options: ['Cualquier interesado externo', 'El Product Owner', 'El Scrum Master de forma unilateral', 'El equipo de desarrollo por votación'], correct: 1, explanation: 'En Scrum, solo el Product Owner tiene la autoridad para cancelar un Sprint si el objetivo se vuelve obsoleto.' },
    { id: 'CAPM-DEMO-016', domain: 'Análisis de negocio', topic: 'Validación', difficulty: 'avanzado', prompt: 'Una solución cumple todas las especificaciones, pero no resuelve la necesidad del usuario. ¿Qué distinción explica mejor el problema?', options: ['La verificación técnica garantiza siempre el valor', 'Cumplir requisitos equivale necesariamente a satisfacer necesidades', 'La validación de necesidades y valor requiere ir más allá de comprobar especificaciones', 'Las pruebas de usuario son innecesarias'], correct: 2, explanation: 'La verificación comprueba conformidad con requisitos; la validación busca confirmar que la solución satisface la necesidad prevista.' },
    { id: 'CAPM-DEMO-017', domain: 'Fundamentos', topic: 'Comunicación', difficulty: 'avanzado', prompt: 'Un interesado clave no recibe la información necesaria y se retrasa una decisión. ¿Qué medida es más apropiada?', options: ['Enviar todos los documentos a todos los interesados sin filtrar', 'Revisar las necesidades de información y el enfoque de comunicaciones con los involucrados', 'Dejar de documentar decisiones', 'Escalar todos los mensajes directamente al patrocinador'], correct: 1, explanation: 'La comunicación eficaz se ajusta a las necesidades de información, la oportunidad y los canales adecuados para cada interesado.' },
    { id: 'CAPM-DEMO-018', domain: 'Análisis de negocio', topic: 'Priorización', difficulty: 'avanzado', prompt: 'Dos funcionalidades tienen el mismo esfuerzo, pero una permite validar primero la hipótesis de negocio más riesgosa. ¿Qué criterio apoya priorizarla?', options: ['Elegir siempre la funcionalidad con nombre más corto', 'Ignorar la incertidumbre de negocio', 'Priorizar el aprendizaje temprano y la reducción de incertidumbre', 'Ordenar únicamente por fecha de creación'], correct: 2, explanation: 'En contextos de incertidumbre, priorizar aprendizaje temprano puede reducir riesgos y mejorar las decisiones sobre el producto.' }
  ],
  glossary: [
    {term:'Proyecto',definition:'Esfuerzo temporal que se lleva a cabo para crear un producto, servicio o resultado único.'},
    {term:'EDT / WBS',definition:'Descomposición jerárquica del alcance total del trabajo del proyecto.'},
    {term:'CPI',definition:'Índice de desempeño de costos: valor ganado (EV) dividido por costo real (AC).'},
    {term:'SPI',definition:'Índice de desempeño del cronograma: valor ganado (EV) dividido por valor planificado (PV).'},
    {term:'Product Backlog',definition:'Lista ordenada y evolutiva del trabajo necesario para mejorar un producto.'},
    {term:'Riesgo',definition:'Evento o condición incierto que, si ocurre, afecta uno o más objetivos.'},
    {term:'Interesado',definition:'Persona, grupo u organización que puede afectar o verse afectado por el proyecto.'},
    {term:'Validación',definition:'Evaluación para determinar si una solución satisface la necesidad prevista.'}
  ]
};
