import type { CampaignNodeDefinition, CertificationPack } from '../core/types';
import { Icon } from './Icons';

export function CampaignView({ course, completed, current, onBack, onStart, onResource, onReview, onReturn }: { course: CertificationPack; completed:string[]; current?:string; onBack:()=>void; onStart:(node:CampaignNodeDefinition)=>void; onResource:(node:CampaignNodeDefinition)=>void; onReview:(node:CampaignNodeDefinition)=>void; onReturn:()=>void }) {
  const campaign=course.campaign; if(!campaign) return <div className="resource-empty"><h1>Campaña no disponible</h1></div>;
  const all=campaign.chapters.flatMap(chapter=>chapter.nodes);
  function status(index:number,node:CampaignNodeDefinition){if(completed.includes(node.id))return'completed';if(node.id===current)return'in-progress';if(index===0||completed.includes(all[index-1].id))return'available';return'pending';}
  function activate(node:CampaignNodeDefinition,index:number){if(status(index,node)==='pending')return;if(node.kind==='resource')onResource(node);else if(node.kind==='review')onReview(node);else onStart(node);}
  return <section className="campaign-view"><header><button className="back-link" onClick={onBack}>← Inicio</button><div><p className="eyebrow">Campaña demostrativa · {course.shortTitle}</p><h1>Ruta de aprendizaje</h1><p>Avanzá con material y preguntas reales del banco. Las recompensas se otorgan una sola vez.</p></div>{current&&<button className="secondary" onClick={onReturn}>Volver al nodo actual</button>}</header><div className="campaign-map">{campaign.chapters.map((chapter,chapterIndex)=><section key={chapter.id} className="campaign-chapter"><div className="chapter-title"><span>{chapterIndex+1}</span><div><h2>{chapter.title}</h2><p>{chapter.description}</p></div></div><div className="campaign-path">{chapter.nodes.map(node=>{const index=all.findIndex(item=>item.id===node.id);const state=status(index,node);return <button id={`node-${node.id}`} key={node.id} className={`campaign-node ${state}`} disabled={state==='pending'} onClick={()=>activate(node,index)}><span className="node-icon"><Icon name={node.kind==='resource'?'book':node.kind==='review'?'cards':node.kind==='challenge'?'exam':'practice'} size={22}/></span><span><small>{state==='completed'?'Completado':state==='in-progress'?'En curso':state==='available'?'Disponible':'Pendiente'} · {node.kind==='challenge'?'Desafío':node.kind==='resource'?'Recurso':node.kind==='review'?'Repaso':'Práctica'}</small><strong>{node.title}</strong>{node.requiredCorrect&&<em>Requisito: {node.requiredCorrect}/{node.questionIds?.length} aciertos</em>}</span><b>{state==='completed'?'✓':state==='pending'?'🔒':'→'}</b></button>})}</div></section>)}</div></section>;
}
