import { useState } from 'react';
import { achievementCatalog, rankFor } from '../core/gamification';
import { globalProfileStats, globalRanks, type AvatarFrame, type AvatarId, type LocalProfile } from '../core/profile';
import { iconPacks, type IconPackId } from '../core/iconPacks';
import { themes, type ThemeId } from '../core/themes';
import type { CertificationPack, StudyProgress } from '../core/types';
import type { HomeStyle } from './GameHome';
import { Avatar } from './Avatar';
import { Icon } from './Icons';

const avatars:{id:AvatarId;name:string}[]=[{id:'anonymous',name:'Anónimo'},{id:'navigator',name:'Navegante'},{id:'scholar',name:'Estudiante'},{id:'guardian',name:'Guardián'},{id:'builder',name:'Constructor'},{id:'explorer',name:'Explorador'},{id:'terminal',name:'Terminal'},{id:'strategist',name:'Estratega'},{id:'researcher',name:'Investigador'},{id:'pathfinder',name:'Pionero'}];
type ProfileTab='summary'|'achievements'|'certifications'|'settings';
interface Props { profile:LocalProfile;progress:StudyProgress;courses:readonly CertificationPack[];activeCourseId:string;themeId:ThemeId;homeStyle:HomeStyle;iconPack:IconPackId;reducedMotion:boolean;largeText:boolean;onChange:(patch:Partial<LocalProfile>)=>void;onCourse:(id:string)=>void;onBack:()=>void;onProgress:()=>void;onMoreSettings:()=>void;onTheme:(id:ThemeId)=>void;onHomeStyle:(style:HomeStyle)=>void;onIconPack:(id:IconPackId)=>void;onToggle:(key:'reducedMotion'|'largeText',value:boolean)=>void; }

export function ProfileView(props:Props){
 const [tab,setTab]=useState<ProfileTab>('summary');const [avatarOpen,setAvatarOpen]=useState(false);const stats=globalProfileStats(props.progress);const level=globalRanks.findIndex(rank=>rank.name===stats.current.name)+1;const availableFrames:AvatarFrame[]=['plain',...(stats.xp>=200?['bronze' as const]:[]),...(stats.xp>=600?['silver' as const]:[]),...(stats.xp>=1200?['gold' as const]:[])];const rankProgress=stats.next?Math.round((stats.xp-stats.current.xp)/(stats.next.xp-stats.current.xp)*100):100;
 return <section className="profile-view profile-center"><button className="back-link" onClick={props.onBack}>← <span>Inicio</span></button><div className="profile-scroll">
  <header className="profile-hero profile-game-hero"><button className="profile-avatar-button" onClick={()=>setAvatarOpen(value=>!value)} aria-expanded={avatarOpen} aria-label="Cambiar avatar"><Avatar id={props.profile.avatar} frame={props.profile.frame} size={104}/><span>Editar</span></button><div><p className="eyebrow">Perfil local · Nivel {level}</p><h1>{stats.current.name}</h1><strong>{stats.xp} XP global</strong><div className="mini-progress"><i style={{width:`${rankProgress}%`}}/></div><small>{stats.next?`${stats.next.xp-stats.xp} XP para ${stats.next.name}`:'Rango máximo alcanzado'}</small></div></header>
  {avatarOpen&&<section className="avatar-picker-panel"><div className="avatar-gallery">{avatars.map(item=><button key={item.id} className={props.profile.avatar===item.id?'active':''} onClick={()=>{props.onChange({avatar:item.id});setAvatarOpen(false)}}><Avatar id={item.id} frame={props.profile.frame}/><span>{item.name}</span></button>)}</div><div className="frame-picker" aria-label="Marcos desbloqueados">{availableFrames.map(frame=><button key={frame} className={props.profile.frame===frame?'active':''} onClick={()=>props.onChange({frame})}>{frame==='plain'?'Simple':frame==='bronze'?'Bronce':frame==='silver'?'Plata':'Oro'}</button>)}</div></section>}
  <div className="profile-tabs" role="tablist">{([['summary','Resumen'],['achievements','Logros'],['certifications','Certificaciones'],['settings','Configuración']] as [ProfileTab,string][]).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  <div className="profile-tab-panel">
   {tab==='summary'&&<><section className="global-metrics profile-metrics"><article><Icon name="target"/><span>Intentos</span><strong>{stats.attempts}</strong></article><article><Icon name="play"/><span>Sesiones</span><strong>{stats.sessions}</strong></article><article><Icon name="chart"/><span>Precisión</span><strong>{stats.attempts?Math.round(stats.correct/stats.attempts*100)+'%':'—'}</strong></article><article><Icon name="trophy"/><span>Logros</span><strong>{stats.unlocked}</strong></article></section><button className="profile-progress-link" onClick={props.onProgress}><Icon name="progress"/><span><strong>Ver progreso detallado</strong><small>Errores, niveles y estadísticas por curso</small></span><Icon name="arrow"/></button></>}
   {tab==='achievements'&&<section className="global-achievements profile-achievements">{props.courses.flatMap(course=>achievementCatalog.map(item=>{const state=props.progress.courses[course.id]?.achievements[item.id];return <article key={`${course.id}-${item.id}`} className={state?.unlockedAt?'unlocked':''}><Icon name={state?.unlockedAt?'trophy':'target'} size={22}/><span>{course.shortTitle}</span><strong>{item.title}</strong><p>{item.description}</p><small>{state?.progress??0}/{item.target}{state?.unlockedAt?' · Completado':' · Pendiente'}</small></article>}))}</section>}
   {tab==='certifications'&&<section className="profile-certifications">{props.courses.map(course=>{const item=props.progress.courses[course.id];const rank=rankFor(item?.xp??0);return <button key={course.id} className={props.activeCourseId===course.id?'active':''} onClick={()=>props.onCourse(course.id)}><Icon name={course.theme.icon} size={30}/><span><strong>{course.shortTitle}</strong><small>{rank.current.name} · {item?.xp??0} XP</small></span><b>{props.activeCourseId===course.id?'Activa':'Elegir'}</b></button>})}</section>}
   {tab==='settings'&&<section className="profile-settings"><h2>Apariencia</h2><div className="profile-choice-grid">{themes.map(theme=><button key={theme.id} className={props.themeId===theme.id?'active':''} onClick={()=>props.onTheme(theme.id)}><i style={{background:theme.accent}}/><span>{theme.name}</span></button>)}</div><h2>Estilo de Inicio</h2><div className="profile-segment">{(['minimal','adventure','dashboard'] as HomeStyle[]).map(style=><button key={style} className={props.homeStyle===style?'active':''} onClick={()=>props.onHomeStyle(style)}>{style}</button>)}</div><h2>Pack de iconos</h2><div className="icon-pack-grid">{iconPacks.map(pack=><button key={pack.id} disabled={pack.status==='placeholder'} className={props.iconPack===pack.id?'active':''} onClick={()=>props.onIconPack(pack.id)}><Icon name={pack.id==='terminal'?'practice':pack.id==='fantasy'?'trophy':pack.id==='strategy'?'map':'cards'}/><span><strong>{pack.name}</strong><small>{pack.status==='placeholder'?'Próximamente':pack.description}</small></span></button>)}</div><div className="profile-toggles"><label><span><strong>Texto ampliado</strong><small>Mejora la legibilidad.</small></span><input type="checkbox" checked={props.largeText} onChange={event=>props.onToggle('largeText',event.target.checked)}/></label><label><span><strong>Reducir movimiento</strong><small>Minimiza las animaciones.</small></span><input type="checkbox" checked={props.reducedMotion} onChange={event=>props.onToggle('reducedMotion',event.target.checked)}/></label></div><button className="profile-progress-link" onClick={props.onMoreSettings}><Icon name="settings"/><span><strong>Opciones avanzadas</strong><small>Modo de color, densidad, PWA y acerca de Study Hub</small></span><Icon name="arrow"/></button></section>}
  </div>
 </div></section>;
}
