import { achievementCatalog, rankFor } from '../core/gamification';
import { globalProfileStats, type AvatarFrame, type AvatarId, type LocalProfile } from '../core/profile';
import type { CertificationPack, StudyProgress } from '../core/types';
import { Avatar } from './Avatar';

const avatars: {id:AvatarId;name:string}[] = [{id:'anonymous',name:'Anónimo'},{id:'navigator',name:'Navegante'},{id:'scholar',name:'Estudiante'},{id:'guardian',name:'Guardián'},{id:'builder',name:'Constructor'},{id:'explorer',name:'Explorador'},{id:'terminal',name:'Terminal'},{id:'strategist',name:'Estratega'},{id:'researcher',name:'Investigador'},{id:'pathfinder',name:'Pionero'}];

export function ProfileView({ profile, progress, courses, onChange, onBack }: { profile: LocalProfile; progress: StudyProgress; courses: readonly CertificationPack[]; onChange:(patch:Partial<LocalProfile>)=>void; onBack:()=>void }) {
  const stats = globalProfileStats(progress);
  const availableFrames: AvatarFrame[] = ['plain', ...(stats.xp >= 200 ? ['bronze' as const] : []), ...(stats.xp >= 600 ? ['silver' as const] : []), ...(stats.xp >= 1200 ? ['gold' as const] : [])];
  return <section className="profile-view"><button className="back-link" onClick={onBack}>← Volver</button><div className="profile-scroll"><header className="profile-hero"><Avatar id={profile.avatar} frame={profile.frame} size={86}/><div><p className="eyebrow">Perfil guardado en este dispositivo</p><h1>{profile.alias || 'Estudiante anónimo'}</h1><strong>{stats.current.name} · {stats.xp} XP global</strong>{stats.next && <small>{stats.next.xp-stats.xp} XP para {stats.next.name}</small>}</div></header><section className="profile-editor"><label><span>Alias opcional</span><input maxLength={24} placeholder="Estudiante anónimo" value={profile.alias} onChange={event=>onChange({alias:event.target.value})}/></label><fieldset><legend>Avatar</legend><div className="avatar-gallery">{avatars.map(item=><button key={item.id} className={profile.avatar===item.id?'active':''} onClick={()=>onChange({avatar:item.id})}><Avatar id={item.id} frame={profile.frame}/><span>{item.name}</span></button>)}</div></fieldset><fieldset><legend>Marco desbloqueado por XP real</legend><div className="frame-picker">{availableFrames.map(frame=><button key={frame} className={profile.frame===frame?'active':''} onClick={()=>onChange({frame})}>{frame==='plain'?'Simple':frame==='bronze'?'Bronce':frame==='silver'?'Plata':'Oro'}</button>)}</div></fieldset></section><section className="global-metrics"><article><span>Intentos reales</span><strong>{stats.attempts}</strong></article><article><span>Sesiones</span><strong>{stats.sessions}</strong></article><article><span>Precisión</span><strong>{stats.attempts?Math.round(stats.correct/stats.attempts*100)+'%':'—'}</strong></article><article><span>Logros</span><strong>{stats.unlocked}</strong></article></section><section className="course-ranks"><h2>Rangos por certificación</h2>{courses.map(course=>{const item=progress.courses[course.id];const rank=rankFor(item?.xp??0);return <article key={course.id}><span>{course.shortTitle}</span><strong>{rank.current.name}</strong><small>{item?.xp??0} XP</small></article>;})}</section><section className="global-achievements"><h2>Galería de logros reales</h2>{courses.flatMap(course=>achievementCatalog.map(item=>{const state=progress.courses[course.id]?.achievements[item.id];return <article key={`${course.id}-${item.id}`} className={state?.unlockedAt?'unlocked':''}><span>{course.shortTitle}</span><strong>{item.title}</strong><p>{item.description}</p><small>{state?.progress??0}/{item.target}{state?.unlockedAt?` · ${new Date(state.unlockedAt).toLocaleDateString()}`:' · Pendiente'}</small></article>}))}</section></div></section>;
}
